[tool.poetry]
name = "fastapi-project"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
fastapi = {extras = ["standard"], version = "^0.115.11"}
uvicorn = "^0.34.0"
sqlalchemy = "^2.0.39"
pydantic = "^2.10.6"
jinja2 = "^3.1.6"
alembic = "^1.15.1"
python-multipart = "^0.0.20"

[tool.poetry.scripts]
start = "uvicorn main:app --reload"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
